### ISSUE TITLE
If MIRROR_{name}_CACHE_EXPIRY is not specified, is the repository specified expiry used?

### ISSUE THREAD

**Issue by fizzyduck** [isaaceindhoven/velocita-proxy#1]
Thanks for this great project.

I had a question around expiry of repo packages.

I have not set the MIRROR_{name}_CACHE_EXPIRY parameter on the Docker image but although I downloaded some packages from a repo yesterday, when I go to fetch them today via the cache, they are all listed as upstream ... [EXPIRED].

Would specifying MIRROR_{name}_CACHE_EXPIRY override the repo set expiry?

**Comment by GMTA** [comment]
Hi @fizzyduck, glad you like it!

The `_CACHE_EXPIRY` parameter, when not set, defaults to 10 years and only determines how the cache works, not how expiry information from upstream is processed.

The upstream resource is revalidated, but if it no longer exists, a stale cache will be served as long as the expiry time has not been reached. In your case, you should get that stale cache.

**Comment by fizzyduck** [comment]
Thanks for the information.

In my case it looks like the upstream repo is setting a short expiry (1day) even though the resource hasn't actually changed. I'd like to be able to override the expiry so that I'm not contacting the upstream repo every day.

Is that something that might be possible?

**Comment by GMTA** [comment]
The upstream resource should actually only be revalidated if a conditional `GET` request is performed (e.g. with an `If-Modified-Since` header).

Expiry information from upstream should essentially be ignored since we [ignore the `Expires` header](https://github.com/isaaceindhoven/velocita-proxy/blob/3cfd5da255a8d8b9c5ba61ade3f4e6c7a7d2f02e/proxy/templates/proxy.conf.erb#L75). But maybe we missed a case there, could you provide a URL or the response headers from the upstream resource?

**Comment by GMTA** [comment]
It would be nice to have a `_CACHE_ALLOW_REVALIDATE` setting (or similar) to set the `proxy_cache_revalidate` setting on a per-proxy basis.

**Comment by GMTA** [comment]
Hi @fizzyduck, could you please try the new `v3.0.0` release of the image? It has support for a new `*_ALLOW_REVALIDATE` setting which prevents requests going out to upstream when conditional requests are received.

**Comment by fizzyduck** [comment]
@GMTA Sorry for the long delay, I have tried v3 and so far it seems to be working as expected, so thank you!

**Comment by GMTA** [comment]
Great to hear @fizzyduck !
