### ISSUE TITLE
Mirror Basic Authorization with special chars

### ISSUE THREAD

**Issue by p24-max** [isaaceindhoven/velocita-proxy#5]
When the password contains special chars (eg. = or :), auth fails and velocita responds with 401.
When having = in the password, whole password in docker-compose must be quoted (").
As the password is working (request works with postman and with composer without velocita), I think there is a bug in velocita.

**Comment by GMTA** [comment]
How exactly are you configuring these credentials? Via `.env`, a `docker run` argument or directly in the `docker-compose.yml` file?

**Comment by p24-max** [comment]
Currently, its configured in `docker-compose.yml` on my machine. Spinning up with docker-compose up.

**Comment by GMTA** [comment]
Alright, so you are bound to the YAML syntax of that file. Are you configuring the environment variable for the basic authorization password through a YAML dictionary (i.e. `MIRROR_BLA_AUTH_PASSWORD: mypass`) or a YAML list (i.e. `- MIRROR_BLA_AUTH_PASSWORD=mypass`)?

**Comment by p24-max** [comment]
`- MIRROR_BLA_AUTH_PASSWORD="mypass=with_special:chars"`

**Comment by GMTA** [comment]
You are passing an environment variable as a list entry, which is parsed by Docker Compose further down the line. The way you quote that value right now _should_ not work correctly; can you try either one of these variants?

```
environment:
- "MIRROR_BLA_AUTH_PASSWORD=mypass=with_special:chars"

# or:

environment:
  MIRROR_BLA_AUTH_PASSWORD: "mypass=with_special:chars"
```

**Comment by p24-max** [comment]
arghh. Layer8 issue :/ 

`- "MIRROR_BLA_AUTH_PASSWORD=mypass=with_special:chars"`
This works great 🤩
Thanks for your support!
