### ISSUE TITLE
[Request] Dependency monitoring

### ISSUE THREAD

**Issue by Tiippex** [isaaceindhoven/velocita-proxy#6]
Hello,

I started using your proxy because I quite often had the problem that github/packagist messed up some dependencies for a short time (which is already quite annoying).

Now, I'm caching dependencies nearly forever. This solved my issue with broken dependencies.

Caching dependencies forever has the bad taste of not knowing what happens with the dependency on the remote site. I would like to know what happens to the dependency.
Is it possible to add some kind of monitoring to the proxy which informs the plugin during an install, whenever a dependency gets deleted or is not available for some reason?

Regards
Max

**Comment by GMTA** [comment]
Hi @Tiippex,

I'm unsure if and how such functionality should land within the Composer plugin, although I agree with you that it would be good to know if there is something wrong with upstream packages.

I did predict something like this could come in handy in the future, which is way I extended the default logging with upstream information:
https://github.com/isaaceindhoven/velocita-proxy/blob/9fb51dd904aae0c536f5c765b5627ab6f19f89ed/proxy/templates/proxy.conf.erb#L53

That is, you should be able to monitor the container's output with something like Loki + Grafana, and trigger alerts on any suspicious upstream statuses. Would that help you?

**Comment by Tiippex** [comment]
Hey @GMTA,

thank you, thats alright :)
